### ISSUE TITLE
Incorrect deadline after a change from CEST to CET

### ISSUE THREAD

**Issue by antoninkriz** [keombre/progtest-theme#34] opened 2020-10-25 20:39 UTC
Deadlines are one hour shorter than with the Original theme (or with addon removed) but it's correct in the assignment's detail
![image](https://user-images.githubusercontent.com/15214494/97118493-68c84800-170a-11eb-844b-d6d93901741a.png)
![image](https://user-images.githubusercontent.com/15214494/97118501-81386280-170a-11eb-8c31-905b99807786.png)
![image](https://user-images.githubusercontent.com/15214494/97118556-dc6a5500-170a-11eb-8645-5759d1faa32f.png)
![image](https://user-images.githubusercontent.com/15214494/97118565-e4c29000-170a-11eb-9f41-cf30674fbe29.png)

**Comment by keombre** [comment] 2020-10-26 13:58
This should be an easy fix.
This is caused by the (apparently improper) usage of the new Progtest API.

**Comment by keombre** [comment] 2020-10-26 15:06
Should be fixed in 97e3cb9c6154413fdf407984af08e8cf9b4f02c0

**Closed as completed** 2020-10-26 15:24 UTC
Labels: bug
